### ISSUE TITLE
Bundle Custom Location

### ISSUE THREAD

**Issue by GeekMasher** [advanced-security/codeql-bundle-action#1]
Right now the Action pulls from the `github/codeql-action` repository. It would be great to be able to point to an external CodeQL bundle created by the community so that if a user wants to build on another bundle, you could specify it.

### Solution

The values in the [`bundle.ts`](https://github.com/advanced-security/codeql-bundle-action/blob/main/src/bundle.ts#L39) should come from the `action.yml` (default value is `github/codeql-action`).

```yaml
- name: CodeQL bundle
    id: codeql-bundle
    uses: advanced-security/codeql-bundle-action@main
    with:
        packs: "geekmasher/python"
        bundle: advanced-security/codeql-queries
        # or a link?
        bundle: https://s3.amazonaws.com/<bucket>/<object>
```

This also helps if users store a version on CodeQL Bundle already in GitHub Packages, S3 bucket, Artifactory, etc.

Suggestions for other solutions are welcome too.
